version: 2
jobs:
  build_apps:
    docker:
      - image: electronuserland/builder:wine
    steps:
      - checkout
      - run:
          command: yarn install
          name: Install dependencies
      - run:
          command: yarn release:win
          name: Build Windows app
      - run:
          command: yarn release:mac
          name: Build MacOS Silicon app

workflows:
  version: 2
  build:
    jobs:
      - build_apps
