version: 2.1
orbs:
  node: circleci/node@5.0.2


jobs:
  deploy:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn dist
          name: Build app
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

workflows:
  test_my_app:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
