version: 2.1
orbs:
  node: circleci/node@5.1.0


jobs:
  deploy:
    executor: node/default
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '18'
      - run:
          command: sudo apt-get install --no-install-recommends -y libopenjp2-tools
          name: Install libopenjp2-tools
      - run:
          command: yarn -v
          name: Check yarn version
      - run:
          command: yarn install
          name: Install dependencies
      - run:
          command: yarn make:win
          name: Build app
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

workflows:
  build_apps:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
