version: 2
jobs:
  build_windows:
    docker:
      - image: electronuserland/builder:wine
    steps:
      - checkout
      - run:
          command: yarn install
          name: Install dependencies
      - run:
          command: yarn make:win
          name: Build Windows app

workflows:
  version: 2
  build:
    jobs:
      - build_windows
