version: 2.1
orbs:
  node: circleci/node@5.1.0


jobs:
  deploy:
    executor: node/default
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '18'
      - run:
          command: yarn -v
          name: Check yarn version
      - run:
          command: yarn install
          name: Install dependencies
      - run:
          command: yarn dist
          name: Build app
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

workflows:
  test_my_app:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
